version: '3.3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    tty: true
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./db_data:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      DB_HOST: 'db'
      DB_DATABASE: 'db'
      DB_USER: 'user'
      DB_PASSWD: 'password'
    ports:
      - '8000:80'
    expose:
      - '80'
    links:
      - db
    depends_on:
      - db
    


volumes:
  db_data:
